# 数据库配置
server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xmx
    password: xmxpassword
    url: jdbc:mysql://192.168.88.141:3306/express-delivery?useUnicode=true&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
